import { StyleSheet } from "react-native";
export const headerStyle = StyleSheet.create({
container:{
    margin: 0,
    padding: 0,
    paddingTop: 20,
    flex: 1,
    fontFamily: 'oswald',
},
header:{
    position: 'relative',
    top: 10,
    height: 60,
    marginBottom: 0,
    paddingTop: 5,
    flexDirection: 'row',
    textAlign: 'center',
    alignItems: 'baseline', 
    borderRadius: 3,
    backgroundColor: 'fffff',
    width: '100%',
},
circle: {
    width: 40,
    height: 40,
    left: 15,
    position: 'relative',
    borderRadius: 40, 
    alignSelf: 'center',
    display: 'flex',
    overflow: 'hidden',
  },
  headerText:{
    fontWeight: '700',
    marginLeft: 10,
    display: 'flex',
    fontSize: 13,
    color: 'black',
    alignSelf: 'center',
    left: 20,
    fontFamily: 'oswald',
    alignItems: 'baseline',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  about:{
    display: 'flex',
    flexDirection: 'row',
    paddingTop: 10,
  },
  barcode:{
    display: 'flex',
  },
  help:{
    width: 30,
    height: 30,
    right: 30,
    position: 'relative',
    top: 10,
    borderRadius: 30,
    fontFamily: 'oswald',
    display: 'flex',
    backgroundColor: 'snow',
    position: 'absolute',
    alignSelf: 'center',
    borderColor: 'red',
    borderWidth: 2,
  },
  helpText:{
    alignSelf: 'center',
    display: 'flex',
    top: -5.5,
    position: 'relative',
    fontFamily: 'oswald',
    fontSize: 20,
  },
});
