import { StyleSheet } from "react-native";
export const Mstyle = StyleSheet.create({
    mainContainer: {
        flex: 1,
        display: "flex",
        alignItems: 'center',
        position: 'relative',
        top: 12,
    },
    subject:{
        position: 'relative',
        borderWidth: 3,
        width: 360,
        height: 80,
        borderRadius: 30,
        borderColor: '#0F6CBF',
        backgroundColor: '#FDFDFD',
        margin: 20,
    },
    subjectData:{
        position: 'relative',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row',
        left: 20,
        top: 20,
    },
    subjectName:{
        fontSize: 18,
        fontStyle: 'regular',
        fontFamily: 'oswald',
    },
    stick:{
        fontSize: 20,
        fontStyle: 'regular',
        fontFamily: 'oswald',
    },
    teacher:{
        fontSize: 18,
        fontStyle: 'regular',
        fontFamily: 'oswald',
    },
    attendance:{
        position: 'relative',
        flexDirection: 'row',
        display: 'flex',
        top: 10,
        borderWidth:3,
        width: 190,
        height:40,
        textAlign: 'center',
        alignItems: 'center',
        justifyContent: 'space-around',
        borderRadius: 30,
        margin: 10,
        alignSelf: 'center',
        justifyContent: 'baseline',
    },
    attendanceText:{
        fontSize: 16,
        fontFamily: 'oswald',
        marginRight: 40,
        paddingLeft: 20,
    },
    percentage:{
        fontSize: 16,
        fontFamily: 'oswald',
    },
    modalWindow:{
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    subjectWindow:{
        width: 350,
        padding: 20, 
        backgroundColor: 'white',
        borderRadius: 10,
        gap: 15, 
    },
    btnGroup:{
        position: 'relative',
        justifyContent: 'space-between',
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
    }
    ,
    goToBtn:{
        position: 'relative',
        width: 150,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 15,
        backgroundColor: '#0F6CBF',
    },
    closeBtn:{
        position: 'relative',
        width: 150,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 15,
        backgroundColor: '#757575',
    },
    modalText:{
        color: 'white',
        fontSize: 16,
        fontFamily: 'oswald',
        bottom: 2,
    }
});
